# Generated by Assembly Auto-Compiler by Alex O'Neill
# Setup
    .equ            LAST_RAM_WORD, 0x007FFFFC
    .global         _start
    .org            0x00000000
    .text

# Entry point
_start:
    movia           sp, LAST_RAM_WORD
    ldw             r3, thing(r0)
    ldw             r4, otherThing(r0)
    add             r5, r3, r4
_end:
    br              _end

# Word-Aligned Variables
    .org            0x00001000

thing:
    .word           3
otherThing:
    .word           5

# End of Assembly Source
    .end