# Generated by Assembly Auto-Compiler by Alex O'Neill
# Setup
    .equ            LAST_RAM_WORD, 0x007FFFFC
    .global         _start
    .org            0x00000000
    .text

# Entry point
_start:
    movia           sp, LAST_RAM_WORD
    call            DoStuff
    call            DogSrock
_end:
    br              _end

# ========== DoStuff ==========
DoStuff:
    br              ds_ret
ds_ret:
    ret

# ========== DogSrock ==========
DogSrock:
    subi            sp, sp, 4
    stw             r10, 0(sp)

    movi            r10, 1234
    ble             r10, r0, ds1_if1
    mov             r2, r10
    br              ds1_ret
ds1_if1:
ds1_ret:

    ldw             r10, 0(sp)
    addi            sp, sp, 4
    ret

# End of Assembly Source
    .end