# Generated by Assembly Auto-Compiler by Alex O'Neill
# Setup
    .equ            LAST_RAM_WORD, 0x007FFFFC
    .global         _start
    .org            0x00000000
    .text

# Entry point
_start:
    movia           sp, LAST_RAM_WORD
    movi            r5, 1000
    movi            r3, 0
    movi            r4, 1
    movi            r6, 0
    # Loop until back to zero
_while1:
    subi            r5, r5, 1
    # decrement r3 and reset to 5
    bne             r3, r0, _if1
    movi            r3, 5
_if1:
    subi            r3, r3, 1
    # decrement r4 and reset to 3
    bne             r4, r0, _if2
    movi            r4, 3
_if2:
    subi            r4, r4, 1
    # if either counter is zero, add the result
    mul             r7, r3, r4
    bne             r7, r0, _if3
    add             r6, r6, r5
_if3:
    bgt             r5, r0, _while1
_end:
    br              _end

# End of Assembly Source
    .end