# Generated by Assembly Auto-Compiler by Alex O'Neill
# Setup
    .equ            LAST_RAM_WORD, 0x007FFFFC
    .global         _start
    .org            0x00000000
    .text

# Entry point
_start:
    movia           sp, LAST_RAM_WORD
_end:
    br              _end

# Word-Aligned Variables
    .org            0x00001000

someValue:
    .skip           4
four:
    .word           4
aList:
    .word           1, 2, 3, 4, 5

# Random Variables

anotherValue:
    .skip           1
seven:
    .byte           7
otherList:
    .byte           5, 4, 3, 2, 1
bigVar:
    .skip           1234

# End of Assembly Source
    .end