# Generated by Assembly Auto-Compiler by Alex O'Neill
# Setup
    .equ            LAST_RAM_WORD, 0x007FFFFC
    .global         _start
    .org            0x00000000
    .text

# Entry point
_start:
    movia           sp, LAST_RAM_WORD
    movi            r3, 4
    mov             r4, r3
    ldw             r5, x(r0)
    stw             r3, x(r0)
    add             r5, r5, r3
_end:
    br              _end

# Word-Aligned Variables
    .org            0x00001000

x:
    .skip           4

# End of Assembly Source
    .end