# Generated by Assembly Auto-Compiler by Alex O'Neill
# Setup
    .equ            LAST_RAM_WORD, 0x007FFFFC
    .global         _start
    .org            0x00000000
    .text

# Entry point
_start:
    movia           sp, LAST_RAM_WORD
    ldw             r2, x(r0)
    addi            r2, r2, 3
    subi            r2, r2, 6
    muli            r2, r2, 132
    ldw             r3, y(r0)
    add             r3, r3, r0
    subi            r3, r3, 234
    muli            r3, r3, 24
    div             r3, r3, r2
_end:
    br              _end

# Word-Aligned Variables
    .org            0x00001000

x:
    .word           31234
y:
    .word           4

# End of Assembly Source
    .end