# Generated by Assembly Auto-Compiler by Alex O'Neill
# Setup
    .equ            LAST_RAM_WORD, 0x007FFFFC
    .global         _start
    .org            0x00000000
    .text

# Entry point
_start:
    movia           sp, LAST_RAM_WORD
    add             r2, r3, r4
    sub             r4, r1, r3
    div             r3, r1, sp
    mul             r0, sstatus, r0
_end:
    br              _end

# End of Assembly Source
    .end